default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username:
  password:

development:
  <<: *default
  database: db/lifewild_dev

test:
  <<: *default
  database: db/lifewild_test

production:
  <<: *default
  database: db/lifewild_prod
